version: '3'


services:
  frontend:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./TodoFront/dist:/usr/share/nginx/html
      - ./docker/volumes/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
  api:
    build:
      dockerfile: ./docker/dockerfiles/TodoBack/Dockerfile
      context: .
    hostname: "todoapp"
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    volumes:
      - ./TodoBack:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'app'
      MYSQL_DATABASE: 'basf-todo-app'